version: "3.8"
services:
  mysqldb:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root #indisponsable pour la conteneurisation
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
  app-achat:
    image: "braiekali/achat:1.0.0"
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # - "spring.jpa.hibernate.ddl-auto": "update"
      # - "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
    restart: unless-stopped
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
volumes:
  db:
